name: build and test
on:  
  pull_request:
    branches: 
    - Development
    - Preprod
    - Release
    paths-ignore:
    - 'README.md'
  workflow_dispatch:
env:
  DOTNET_VERSION: '6.0.x'
  
defaults:
  run:
    working-directory: CarRentalServiceAPI
  
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
            
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Install FE.SqlServer Nuget Package
      run: dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 7.0.1
    - name: Install FE.Tools Nuget Package
      run: dotnet add package Microsoft.EntityFrameworkCore.Tools --version 7.0.1
      
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal